FROM python:3.9-slim

WORKDIR /app

# 1. Copiamos primero los requerimientos (para aprovechar la caché de Docker)
COPY requirements.txt .

# 2. Instalamos las dependencias desde el archivo
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copiamos el resto del código
COPY . .

EXPOSE 5000

CMD ["python", "main.py"]